### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by ta-shi** [answerdash/answerdash-android-sdk-demo#1]
Could not get resource 'https://repo.answerdash.com/releases/com/answerdash/android/answerdash-sdk/0.2.3/answerdash-sdk-0.2.3.pom'.
            > Could not GET 'https://repo.answerdash.com/releases/com/answerdash/android/answerdash-sdk/0.2.3/answerdash-sdk-0.2.3.pom'.
               > sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

**Comment by cconnors1515** [comment]
@ta-shi Just resolved this issue. Please verify it is now working

**Comment by ta-shi** [comment]
Thank you 😃
